### ISSUE TITLE
Package breaks minification

### ISSUE THREAD

**Issue by wizonesolutions** [Goltfisch/meteor-hotjar#1]
Just narrowed down a production minification breakage to this package. It seems to make it to that Spacebars isn't included in time (or isn't namespaced properly), and that confuses all packages that depend on it and makes them error out.

I'm investigating what's going on and will submit a PR if I can figure it out.

Usually, minification errors are apparently because of missing semicolons. So I'm going to look into that first.

**Comment by wizonesolutions** [comment]
Hrm. If I clone the code into the `packages` directory, then I can't reproduce the issue. Seeing if it re-occurs when I re-add the package.

EDIT: It does.

**Comment by wizonesolutions** [comment]
So this is what gets generated in the package:

```
(function () {

/////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                 //
// packages/goltfisch:hotjar/client/hotjar.js                                                      //
//                                                                                                 //
/////////////////////////////////////////////////////////////////////////////////////////////////////
                                                                                                   //
(function(h,o,t,j,a,r){                                                                            // 1
  h.hj=h.hj||function(){(h.hj.q=h.hj.q||[]).push(arguments)};                                      // 2
  h._hjSettings={hjid:Meteor.settings.public.hotjar.hjid,hjsv:Meteor.settings.public.hotjar.hjsv}; // 3
  a=o.getElementsByTagName('head')[0];                                                             // 4
  r=o.createElement('script');r.async=1;                                                           // 5
  r.src=t+h._hjSettings.hjid+j+h._hjSettings.hjsv;                                                 // 6
  a.appendChild(r);                                                                                // 7
})(window,document,'//static.hotjar.com/c/hotjar-','.js?sv=');                                     // 8
                                                                                                   // 9
/////////////////////////////////////////////////////////////////////////////////////////////////////

}).call(this);
```

It looks OK, although one issue I can see is how it checks `Meteor.settings` and doesn't appear to guard against those settings not existing. But were this case, it would also happen when including the package manually.

Ah, wait. I just looked at the _first_ error I get:

```
Uncaught TypeError: Cannot read property 'public' of undefined(anonymous function) @ 1a19312ee26810ef1bc78621d1fee4a68b2b2358.js:formatted:51428(anonymous function) @ 1a19312ee26810ef1bc78621d1fee4a68b2b2358.js:formatted:51437(anonymous function) @ 1a19312ee26810ef1bc78621d1fee4a68b2b2358.js:formatted:51439(anonymous function) @ 1a19312ee26810ef1bc78621d1fee4a68b2b2358.js:formatted:51443
```

And that code is:

``` javascript
  e._hjSettings = {
    hjid: t.settings["public"].hotjar.hjid,
    hjsv: t.settings["public"].hotjar.hjsv
  },
```

So it'd seem that at the point it runs when in production mode, `Meteor.settings` hasn't been defined yet? Maybe `packages`-directory packages are loaded later than `packages`-file packages, and the race condition doesn't happen there?

**Comment by pmuens** [comment]
Hey @wizonesolutions thank you for your issue!
Hmm taht's weird. I'm not able to reproduce it. Basically it is just the hotjar JavaScript file they provide on their page and the parameters are then replaced via a call to the Meteor settings.

Can you maybe upload a repo with a reproduction when you got it reproduced?
Thanks!

**Comment by wizonesolutions** [comment]
@pmuens It seems like putting in our `hotjar` configuration actually fixes it. Perhaps you could make the code a bit more defensive, e.g. `Meteor.settings && Meteor.settings.public && Meteor.settings.public.hotjar && Meteor.settings.public.hotjar.hjid`

Obviously it can be done more elegantly; that's just to communicate my thinking.

I don't know why it doesn't fail if I clone the repo directly. But I think this is the issue...if the package is enabled but nothing's configured in `settings.json`, it fails to read and breaks.

**Comment by wizonesolutions** [comment]
I tried to make a minimal reproduction, but I can't get the same Spacebars failure as I did in ours. It probably requires a number of packages. Since I have a workaround, though, I'll just leave it here as a suggestion to code more defensively in the package. I assume that'd prevent cases like mine.

(I do get the same error from the `hotjar` package of course.)

**Comment by pmuens** [comment]
Thank you. Yes, now I can reproduce it. Missing Settings are really the reason. Thanks for investigating!
